spring:
  datasource:
    url: jdbc:mysql://47.92.72.146:3306/admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
    show-sql: true
    format-sql: true
server:
  port: 8888
  servlet:
    context-path: /api
shiro:
  password:
    hash-iterations: 10 #默认加密次数,在密码匹配和注册两个地方使用
    algorithm-name: sha-1 #加密算法
logging:
  level:
    club.javalearn.admin: debug
debug: true
